// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.3
// source: internal/flexletpb/flexlet_service.proto

package flexletpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlexletServiceClient is the client API for FlexletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlexletServiceClient interface {
	TakeTask(ctx context.Context, in *TakeTaskRequest, opts ...grpc.CallOption) (*TakeTaskResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
	FinishTask(ctx context.Context, in *FinishTaskRequest, opts ...grpc.CallOption) (*FinishTaskResponse, error)
	UpdateFlexlet(ctx context.Context, in *UpdateFlexletRequest, opts ...grpc.CallOption) (*UpdateFlexletResponse, error)
}

type flexletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlexletServiceClient(cc grpc.ClientConnInterface) FlexletServiceClient {
	return &flexletServiceClient{cc}
}

func (c *flexletServiceClient) TakeTask(ctx context.Context, in *TakeTaskRequest, opts ...grpc.CallOption) (*TakeTaskResponse, error) {
	out := new(TakeTaskResponse)
	err := c.cc.Invoke(ctx, "/flex.FlexletService/TakeTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexletServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, "/flex.FlexletService/UpdateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexletServiceClient) FinishTask(ctx context.Context, in *FinishTaskRequest, opts ...grpc.CallOption) (*FinishTaskResponse, error) {
	out := new(FinishTaskResponse)
	err := c.cc.Invoke(ctx, "/flex.FlexletService/FinishTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexletServiceClient) UpdateFlexlet(ctx context.Context, in *UpdateFlexletRequest, opts ...grpc.CallOption) (*UpdateFlexletResponse, error) {
	out := new(UpdateFlexletResponse)
	err := c.cc.Invoke(ctx, "/flex.FlexletService/UpdateFlexlet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlexletServiceServer is the server API for FlexletService service.
// All implementations must embed UnimplementedFlexletServiceServer
// for forward compatibility
type FlexletServiceServer interface {
	TakeTask(context.Context, *TakeTaskRequest) (*TakeTaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	FinishTask(context.Context, *FinishTaskRequest) (*FinishTaskResponse, error)
	UpdateFlexlet(context.Context, *UpdateFlexletRequest) (*UpdateFlexletResponse, error)
	mustEmbedUnimplementedFlexletServiceServer()
}

// UnimplementedFlexletServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlexletServiceServer struct {
}

func (UnimplementedFlexletServiceServer) TakeTask(context.Context, *TakeTaskRequest) (*TakeTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeTask not implemented")
}
func (UnimplementedFlexletServiceServer) UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedFlexletServiceServer) FinishTask(context.Context, *FinishTaskRequest) (*FinishTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishTask not implemented")
}
func (UnimplementedFlexletServiceServer) UpdateFlexlet(context.Context, *UpdateFlexletRequest) (*UpdateFlexletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlexlet not implemented")
}
func (UnimplementedFlexletServiceServer) mustEmbedUnimplementedFlexletServiceServer() {}

// UnsafeFlexletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlexletServiceServer will
// result in compilation errors.
type UnsafeFlexletServiceServer interface {
	mustEmbedUnimplementedFlexletServiceServer()
}

func RegisterFlexletServiceServer(s grpc.ServiceRegistrar, srv FlexletServiceServer) {
	s.RegisterService(&FlexletService_ServiceDesc, srv)
}

func _FlexletService_TakeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexletServiceServer).TakeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flex.FlexletService/TakeTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexletServiceServer).TakeTask(ctx, req.(*TakeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexletService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexletServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flex.FlexletService/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexletServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexletService_FinishTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexletServiceServer).FinishTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flex.FlexletService/FinishTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexletServiceServer).FinishTask(ctx, req.(*FinishTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexletService_UpdateFlexlet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlexletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexletServiceServer).UpdateFlexlet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flex.FlexletService/UpdateFlexlet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexletServiceServer).UpdateFlexlet(ctx, req.(*UpdateFlexletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlexletService_ServiceDesc is the grpc.ServiceDesc for FlexletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlexletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flex.FlexletService",
	HandlerType: (*FlexletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TakeTask",
			Handler:    _FlexletService_TakeTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _FlexletService_UpdateTask_Handler,
		},
		{
			MethodName: "FinishTask",
			Handler:    _FlexletService_FinishTask_Handler,
		},
		{
			MethodName: "UpdateFlexlet",
			Handler:    _FlexletService_UpdateFlexlet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/flexletpb/flexlet_service.proto",
}
