// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/flexletpb/flexlet.proto

package flexletpb

import (
	flex "github.com/nya3jp/flex"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref  *TaskRef  `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Spec *TaskSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetRef() *TaskRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Task) GetSpec() *TaskSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type TaskRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId *flex.TaskId `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId  *flex.JobId  `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *TaskRef) Reset() {
	*x = TaskRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRef) ProtoMessage() {}

func (x *TaskRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRef.ProtoReflect.Descriptor instead.
func (*TaskRef) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRef) GetTaskId() *flex.TaskId {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *TaskRef) GetJobId() *flex.JobId {
	if x != nil {
		return x.JobId
	}
	return nil
}

type TaskSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command *flex.JobCommand `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Inputs  *TaskInputs      `protobuf:"bytes,2,opt,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs *TaskOutputs     `protobuf:"bytes,3,opt,name=outputs,proto3" json:"outputs,omitempty"`
	Limits  *flex.JobLimits  `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_proto_rawDescGZIP(), []int{2}
}

func (x *TaskSpec) GetCommand() *flex.JobCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TaskSpec) GetInputs() *TaskInputs {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *TaskSpec) GetOutputs() *TaskOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TaskSpec) GetLimits() *flex.JobLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type TaskInputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packages []*TaskPackage `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
}

func (x *TaskInputs) Reset() {
	*x = TaskInputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInputs) ProtoMessage() {}

func (x *TaskInputs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInputs.ProtoReflect.Descriptor instead.
func (*TaskInputs) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_proto_rawDescGZIP(), []int{3}
}

func (x *TaskInputs) GetPackages() []*TaskPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

type TaskPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location   *flex.FileLocation `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	InstallDir string             `protobuf:"bytes,2,opt,name=install_dir,json=installDir,proto3" json:"install_dir,omitempty"`
}

func (x *TaskPackage) Reset() {
	*x = TaskPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskPackage) ProtoMessage() {}

func (x *TaskPackage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskPackage.ProtoReflect.Descriptor instead.
func (*TaskPackage) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_proto_rawDescGZIP(), []int{4}
}

func (x *TaskPackage) GetLocation() *flex.FileLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *TaskPackage) GetInstallDir() string {
	if x != nil {
		return x.InstallDir
	}
	return ""
}

type TaskOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdout *flex.FileLocation `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr *flex.FileLocation `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
}

func (x *TaskOutputs) Reset() {
	*x = TaskOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutputs) ProtoMessage() {}

func (x *TaskOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutputs.ProtoReflect.Descriptor instead.
func (*TaskOutputs) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_proto_rawDescGZIP(), []int{5}
}

func (x *TaskOutputs) GetStdout() *flex.FileLocation {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *TaskOutputs) GetStderr() *flex.FileLocation {
	if x != nil {
		return x.Stderr
	}
	return nil
}

var File_internal_flexletpb_flexlet_proto protoreflect.FileDescriptor

var file_internal_flexletpb_flexlet_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x6c, 0x65, 0x78, 0x6c,
	0x65, 0x74, 0x70, 0x62, 0x2f, 0x66, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x66, 0x6c, 0x65, 0x78, 0x1a, 0x0a, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1f, 0x0a, 0x03,
	0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x66, 0x6c, 0x65, 0x78,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x22, 0x0a,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6c,
	0x65, 0x78, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x22, 0x54, 0x0a, 0x07, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x66, 0x12, 0x25, 0x0a, 0x07,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x66, 0x6c, 0x65, 0x78, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64,
	0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0xb6, 0x01, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x70, 0x65, 0x63, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x4a, 0x6f, 0x62,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x28, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x73, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6c,
	0x65, 0x78, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x52, 0x07,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x4a,
	0x6f, 0x62, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73,
	0x22, 0x3b, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x2d,
	0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x22, 0x5e, 0x0a,
	0x0b, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x44, 0x69, 0x72, 0x22, 0x65, 0x0a,
	0x0b, 0x54, 0x61, 0x73, 0x6b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x06,
	0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66,
	0x6c, 0x65, 0x78, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65,
	0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x73, 0x74,
	0x64, 0x65, 0x72, 0x72, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x79, 0x61, 0x33, 0x6a, 0x70, 0x2f, 0x66, 0x6c, 0x65, 0x78, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_flexletpb_flexlet_proto_rawDescOnce sync.Once
	file_internal_flexletpb_flexlet_proto_rawDescData = file_internal_flexletpb_flexlet_proto_rawDesc
)

func file_internal_flexletpb_flexlet_proto_rawDescGZIP() []byte {
	file_internal_flexletpb_flexlet_proto_rawDescOnce.Do(func() {
		file_internal_flexletpb_flexlet_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_flexletpb_flexlet_proto_rawDescData)
	})
	return file_internal_flexletpb_flexlet_proto_rawDescData
}

var file_internal_flexletpb_flexlet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_flexletpb_flexlet_proto_goTypes = []interface{}{
	(*Task)(nil),              // 0: flex.Task
	(*TaskRef)(nil),           // 1: flex.TaskRef
	(*TaskSpec)(nil),          // 2: flex.TaskSpec
	(*TaskInputs)(nil),        // 3: flex.TaskInputs
	(*TaskPackage)(nil),       // 4: flex.TaskPackage
	(*TaskOutputs)(nil),       // 5: flex.TaskOutputs
	(*flex.TaskId)(nil),       // 6: flex.TaskId
	(*flex.JobId)(nil),        // 7: flex.JobId
	(*flex.JobCommand)(nil),   // 8: flex.JobCommand
	(*flex.JobLimits)(nil),    // 9: flex.JobLimits
	(*flex.FileLocation)(nil), // 10: flex.FileLocation
}
var file_internal_flexletpb_flexlet_proto_depIdxs = []int32{
	1,  // 0: flex.Task.ref:type_name -> flex.TaskRef
	2,  // 1: flex.Task.spec:type_name -> flex.TaskSpec
	6,  // 2: flex.TaskRef.task_id:type_name -> flex.TaskId
	7,  // 3: flex.TaskRef.job_id:type_name -> flex.JobId
	8,  // 4: flex.TaskSpec.command:type_name -> flex.JobCommand
	3,  // 5: flex.TaskSpec.inputs:type_name -> flex.TaskInputs
	5,  // 6: flex.TaskSpec.outputs:type_name -> flex.TaskOutputs
	9,  // 7: flex.TaskSpec.limits:type_name -> flex.JobLimits
	4,  // 8: flex.TaskInputs.packages:type_name -> flex.TaskPackage
	10, // 9: flex.TaskPackage.location:type_name -> flex.FileLocation
	10, // 10: flex.TaskOutputs.stdout:type_name -> flex.FileLocation
	10, // 11: flex.TaskOutputs.stderr:type_name -> flex.FileLocation
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_flexletpb_flexlet_proto_init() }
func file_internal_flexletpb_flexlet_proto_init() {
	if File_internal_flexletpb_flexlet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_flexletpb_flexlet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_flexletpb_flexlet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_flexletpb_flexlet_proto_goTypes,
		DependencyIndexes: file_internal_flexletpb_flexlet_proto_depIdxs,
		MessageInfos:      file_internal_flexletpb_flexlet_proto_msgTypes,
	}.Build()
	File_internal_flexletpb_flexlet_proto = out.File
	file_internal_flexletpb_flexlet_proto_rawDesc = nil
	file_internal_flexletpb_flexlet_proto_goTypes = nil
	file_internal_flexletpb_flexlet_proto_depIdxs = nil
}
