// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/flexletpb/flexlet_service.proto

package flexletpb

import (
	flex "github.com/nya3jp/flex"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaitTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *flex.FlexletId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WaitTaskRequest) Reset() {
	*x = WaitTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitTaskRequest) ProtoMessage() {}

func (x *WaitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitTaskRequest.ProtoReflect.Descriptor instead.
func (*WaitTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{0}
}

func (x *WaitTaskRequest) GetId() *flex.FlexletId {
	if x != nil {
		return x.Id
	}
	return nil
}

type WaitTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *WaitTaskResponse) Reset() {
	*x = WaitTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitTaskResponse) ProtoMessage() {}

func (x *WaitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitTaskResponse.ProtoReflect.Descriptor instead.
func (*WaitTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{1}
}

func (x *WaitTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *flex.JobId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTaskRequest) GetId() *flex.JobId {
	if x != nil {
		return x.Id
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{3}
}

type ReturnTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *flex.JobId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReturnTaskRequest) Reset() {
	*x = ReturnTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnTaskRequest) ProtoMessage() {}

func (x *ReturnTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnTaskRequest.ProtoReflect.Descriptor instead.
func (*ReturnTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReturnTaskRequest) GetId() *flex.JobId {
	if x != nil {
		return x.Id
	}
	return nil
}

type ReturnTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnTaskResponse) Reset() {
	*x = ReturnTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnTaskResponse) ProtoMessage() {}

func (x *ReturnTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnTaskResponse.ProtoReflect.Descriptor instead.
func (*ReturnTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{5}
}

type FinishTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *flex.JobId     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result *flex.JobResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FinishTaskRequest) Reset() {
	*x = FinishTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskRequest) ProtoMessage() {}

func (x *FinishTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{6}
}

func (x *FinishTaskRequest) GetId() *flex.JobId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FinishTaskRequest) GetResult() *flex.JobResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type FinishTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishTaskResponse) Reset() {
	*x = FinishTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskResponse) ProtoMessage() {}

func (x *FinishTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskResponse.ProtoReflect.Descriptor instead.
func (*FinishTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{7}
}

type UpdateFlexletSpecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *flex.FlexletId   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec *flex.FlexletSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *UpdateFlexletSpecRequest) Reset() {
	*x = UpdateFlexletSpecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlexletSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlexletSpecRequest) ProtoMessage() {}

func (x *UpdateFlexletSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlexletSpecRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlexletSpecRequest) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFlexletSpecRequest) GetId() *flex.FlexletId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateFlexletSpecRequest) GetSpec() *flex.FlexletSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UpdateFlexletSpecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFlexletSpecResponse) Reset() {
	*x = UpdateFlexletSpecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlexletSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlexletSpecResponse) ProtoMessage() {}

func (x *UpdateFlexletSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flexletpb_flexlet_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlexletSpecResponse.ProtoReflect.Descriptor instead.
func (*UpdateFlexletSpecResponse) Descriptor() ([]byte, []int) {
	return file_internal_flexletpb_flexlet_service_proto_rawDescGZIP(), []int{9}
}

var File_internal_flexletpb_flexlet_service_proto protoreflect.FileDescriptor

var file_internal_flexletpb_flexlet_service_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x6c, 0x65, 0x78, 0x6c,
	0x65, 0x74, 0x70, 0x62, 0x2f, 0x66, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x6c, 0x65, 0x78,
	0x1a, 0x0a, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x70, 0x62,
	0x2f, 0x66, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32,
	0x0a, 0x0f, 0x57, 0x61, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x66, 0x6c, 0x65, 0x78, 0x2e, 0x46, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x32, 0x0a, 0x10, 0x57, 0x61, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x30, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x4a,
	0x6f, 0x62, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30,
	0x0a, 0x11, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x59, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x4a,
	0x6f, 0x62, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e,
	0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x62, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x46, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x49, 0x64,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x46, 0x6c, 0x65, 0x78, 0x6c, 0x65,
	0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x1b, 0x0a, 0x19, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xee, 0x02, 0x0a, 0x0e, 0x46, 0x6c, 0x65,
	0x78, 0x6c, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x57,
	0x61, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x15, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x57,
	0x61, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x66, 0x6c, 0x65, 0x78,
	0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x66,
	0x6c, 0x65, 0x78, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x56, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x65, 0x78, 0x6c,
	0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1e, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x66, 0x6c, 0x65, 0x78, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x65, 0x78, 0x6c, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x79, 0x61, 0x33, 0x6a, 0x70, 0x2f, 0x66,
	0x6c, 0x65, 0x78, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x6c, 0x65,
	0x78, 0x6c, 0x65, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_flexletpb_flexlet_service_proto_rawDescOnce sync.Once
	file_internal_flexletpb_flexlet_service_proto_rawDescData = file_internal_flexletpb_flexlet_service_proto_rawDesc
)

func file_internal_flexletpb_flexlet_service_proto_rawDescGZIP() []byte {
	file_internal_flexletpb_flexlet_service_proto_rawDescOnce.Do(func() {
		file_internal_flexletpb_flexlet_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_flexletpb_flexlet_service_proto_rawDescData)
	})
	return file_internal_flexletpb_flexlet_service_proto_rawDescData
}

var file_internal_flexletpb_flexlet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_flexletpb_flexlet_service_proto_goTypes = []interface{}{
	(*WaitTaskRequest)(nil),           // 0: flex.WaitTaskRequest
	(*WaitTaskResponse)(nil),          // 1: flex.WaitTaskResponse
	(*UpdateTaskRequest)(nil),         // 2: flex.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),        // 3: flex.UpdateTaskResponse
	(*ReturnTaskRequest)(nil),         // 4: flex.ReturnTaskRequest
	(*ReturnTaskResponse)(nil),        // 5: flex.ReturnTaskResponse
	(*FinishTaskRequest)(nil),         // 6: flex.FinishTaskRequest
	(*FinishTaskResponse)(nil),        // 7: flex.FinishTaskResponse
	(*UpdateFlexletSpecRequest)(nil),  // 8: flex.UpdateFlexletSpecRequest
	(*UpdateFlexletSpecResponse)(nil), // 9: flex.UpdateFlexletSpecResponse
	(*flex.FlexletId)(nil),            // 10: flex.FlexletId
	(*Task)(nil),                      // 11: flex.Task
	(*flex.JobId)(nil),                // 12: flex.JobId
	(*flex.JobResult)(nil),            // 13: flex.JobResult
	(*flex.FlexletSpec)(nil),          // 14: flex.FlexletSpec
}
var file_internal_flexletpb_flexlet_service_proto_depIdxs = []int32{
	10, // 0: flex.WaitTaskRequest.id:type_name -> flex.FlexletId
	11, // 1: flex.WaitTaskResponse.task:type_name -> flex.Task
	12, // 2: flex.UpdateTaskRequest.id:type_name -> flex.JobId
	12, // 3: flex.ReturnTaskRequest.id:type_name -> flex.JobId
	12, // 4: flex.FinishTaskRequest.id:type_name -> flex.JobId
	13, // 5: flex.FinishTaskRequest.result:type_name -> flex.JobResult
	10, // 6: flex.UpdateFlexletSpecRequest.id:type_name -> flex.FlexletId
	14, // 7: flex.UpdateFlexletSpecRequest.spec:type_name -> flex.FlexletSpec
	0,  // 8: flex.FlexletService.WaitTask:input_type -> flex.WaitTaskRequest
	2,  // 9: flex.FlexletService.UpdateTask:input_type -> flex.UpdateTaskRequest
	4,  // 10: flex.FlexletService.ReturnTask:input_type -> flex.ReturnTaskRequest
	6,  // 11: flex.FlexletService.FinishTask:input_type -> flex.FinishTaskRequest
	8,  // 12: flex.FlexletService.UpdateFlexletSpec:input_type -> flex.UpdateFlexletSpecRequest
	1,  // 13: flex.FlexletService.WaitTask:output_type -> flex.WaitTaskResponse
	3,  // 14: flex.FlexletService.UpdateTask:output_type -> flex.UpdateTaskResponse
	5,  // 15: flex.FlexletService.ReturnTask:output_type -> flex.ReturnTaskResponse
	7,  // 16: flex.FlexletService.FinishTask:output_type -> flex.FinishTaskResponse
	9,  // 17: flex.FlexletService.UpdateFlexletSpec:output_type -> flex.UpdateFlexletSpecResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_flexletpb_flexlet_service_proto_init() }
func file_internal_flexletpb_flexlet_service_proto_init() {
	if File_internal_flexletpb_flexlet_service_proto != nil {
		return
	}
	file_internal_flexletpb_flexlet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_flexletpb_flexlet_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFlexletSpecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_flexletpb_flexlet_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFlexletSpecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_flexletpb_flexlet_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_flexletpb_flexlet_service_proto_goTypes,
		DependencyIndexes: file_internal_flexletpb_flexlet_service_proto_depIdxs,
		MessageInfos:      file_internal_flexletpb_flexlet_service_proto_msgTypes,
	}.Build()
	File_internal_flexletpb_flexlet_service_proto = out.File
	file_internal_flexletpb_flexlet_service_proto_rawDesc = nil
	file_internal_flexletpb_flexlet_service_proto_goTypes = nil
	file_internal_flexletpb_flexlet_service_proto_depIdxs = nil
}
