FROM golang:1.12 as builder

WORKDIR /build

# Install dependencies first for caching.
COPY go.mod go.sum ./
RUN go mod download

# Build a static binary.
COPY . ./
RUN CGO_ENABLED=0 go install github.com/nya3jp/flex/cmd/flexmaster

FROM alpine

WORKDIR /app
COPY --from=builder /go/bin/flexmaster ./
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
CMD /app/flexmaster
