CREATE TABLE `jobs` (
    `id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    `priority` INT(10) NOT NULL,
    `state` ENUM('PENDING', 'RUNNING', 'FINISHED') NOT NULL DEFAULT 'PENDING',
    `task_uuid` CHAR(36) NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `request` MEDIUMBLOB NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX `jobs_queue` ON `jobs` (`state`, `priority` DESC, `id` ASC);

CREATE TABLE `tasks` (
    `uuid` CHAR(36) PRIMARY KEY,
    `state` ENUM('RUNNING', 'FINISHED') NOT NULL DEFAULT 'RUNNING',
    `flexlet` VARCHAR(128) NOT NULL,
    `started` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `finished` TIMESTAMP NULL,
    `response` MEDIUMBLOB NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE `tags` (
    `tag` VARCHAR(128) PRIMARY KEY,
    `hash` CHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE `flexlets` (
    `name` VARCHAR(128) PRIMARY KEY,
    `state` ENUM('OFFLINE', 'ONLINE') NOT NULL DEFAULT 'OFFLINE',
    `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `cores` INT(10) NOT NULL,
    `data` MEDIUMBLOB NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE `labels` (
    `label` CHAR(128) NOT NULL,
    `job_id` BIGINT(20) NOT NULL,
    PRIMARY KEY (`label`, `job_id` DESC),
    FOREIGN KEY (`job_id`) REFERENCES `jobs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
