CREATE TABLE IF NOT EXISTS `jobs` (
    `id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    `priority` INT(10) NOT NULL,
    `state` ENUM('PENDING', 'RUNNING', 'FINISHED') NOT NULL DEFAULT 'PENDING',
    `flexlet` VARCHAR(128) NULL,
    `queued` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `started` TIMESTAMP NULL,
    `finished` TIMESTAMP NULL,
    `request` MEDIUMBLOB NOT NULL,
    `response` MEDIUMBLOB NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE INDEX `jobs_queue` ON `jobs` (`state`, `priority` DESC, `id` ASC);

CREATE TABLE IF NOT EXISTS `tags` (
    `tag` VARCHAR(128) PRIMARY KEY,
    `hash` CHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
