name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    name: "CI"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: flexuser
          MYSQL_PASSWORD: flexpass
          MYSQL_DATABASE: flextest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -tags=integration -v ./...
        env:
          FLEX_TEST_DB_HOST: localhost:3306
          FLEX_TEST_DB_USER: flexuser
          FLEX_TEST_DB_PASS: flexpass
          FLEX_TEST_DB_NAME: flextest
      - name: Log in to ghcr.io
        if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Flexhub Docker container
        if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          file: docker/flexhub.Dockerfile
          tags: ghcr.io/nya3jp/flexhub:latest
          push: true
      - name: Build and push Flexlet Docker container
        if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          file: docker/flexlet.Dockerfile
          tags: ghcr.io/nya3jp/flexlet:latest
          push: true
