name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: go build -v ./...

  test:
    name: "Test"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: flexuser
          MYSQL_PASSWORD: flexpass
          MYSQL_DATABASE: flextest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test
        run: go test -tags=integration -v ./...
        env:
          FLEX_TEST_DB_HOST: localhost:3306
          FLEX_TEST_DB_USER: flexuser
          FLEX_TEST_DB_PASS: flexpass
          FLEX_TEST_DB_NAME: flextest
