name: Packaging

on:
  push:
    branches: [ main ]

jobs:

  build_and_test:
    name: "Docker push"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: flexuser
          MYSQL_PASSWORD: flexpass
          MYSQL_DATABASE: flextest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -tags=integration -v ./...
        env:
          FLEX_TEST_DB_HOST: localhost:3306
          FLEX_TEST_DB_USER: flexuser
          FLEX_TEST_DB_PASS: flexpass
          FLEX_TEST_DB_NAME: flextest
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Flexhub
        uses: docker/build-push-action@v2
        with:
          file: docker/flexhub.Dockerfile
          tags: ghcr.io/nya3jp/flexhub:latest
          push: true
      - name: Flexlet
        uses: docker/build-push-action@v2
        with:
          file: docker/flexlet.Dockerfile
          tags: ghcr.io/nya3jp/flexlet:latest
          push: true
